Implementação dos Componentes Navbar e Hero
devhatt/devhatt-lp pull request #17
Opened 2024-08-02 23:51 UTC by Luiginicoletti

**Descrição**
Este pull request adiciona os componentes **Navbar** e **Hero** ao projeto.

### Componente Navbar:

Criação do componente Navbar com links de navegação para diferentes seções do site 
_(Home, Features, Benefits, Join Us, FAQ)._

Utilização da biblioteca **framer-motion** para animações suaves ao passar o mouse sobre os links de navegação.
Implementação de um botão de call-to-action "Teste agora" com efeitos de sombra e transição.

Responsividade para diferentes tamanhos de tela, com ajustes de estilo para a versão mobile.

### Componente Hero:

Criação do componente **Hero** com uma seção.

Utilização da biblioteca **framer-motion** para animações de elementos no **Hero**.

Adição de uma animação de onda no background para melhorar a experiência visual.

### Screenshots

<img width="1533" alt="Screenshot 2024-08-02 at 20 51 39" src="https://github.com/user-attachments/assets/3667a942-23d2-4cf7-8011-504ae74a55da">

2024-08-05 11:45 UTC, PiluVitu requested changes

2024-08-05 11:45 UTC, PiluVitu commented on app/octopost/components/Hero.tsx
> +      <div className="flex bg-gradient-to-t to-indigo-500 via-[#805AD5] from-[#E030A3] justify-center items-center h-screen">
Essas cores usadas serão recorrentes na aplicação ? Se sim não seria melhor armazenar a mesmas no tailwindconfig ?

2024-08-05 11:45 UTC, PiluVitu commented on public/teste.svg
Isso é para ser removido ?

2024-08-05 11:45 UTC, PiluVitu commented on public/bg-pattern.svg
Está certo ele está aqui ? ou é apenas teste ?

2024-08-05 12:29 UTC, Luiginicoletti commented on public/teste.svg
Ah é sim, haviam bastantes coisas para ser modificada na real, eu subi o pr pra poder dar continuidade e nao ficar parado, mas vou corrigindo tudo agora.

2024-08-05 12:30 UTC, Luiginicoletti commented on public/bg-pattern.svg
Tambem faz parte do teste, esse bg-pattern deu muito trabalho hahaa, vou arrumar as coisas hoje e subo um novo pr.

2024-08-06 18:07 UTC, k1nha commented on app/octopost/components/components/waves.js
coloca o arquivo como tsx

2024-08-06 18:08 UTC, k1nha commented on app/octopost/components/Navbar.tsx
> +    <div className="backdrop-blue-md fixed top-0 z-[100]  mx-auto flex h-[77px] w-full items-center  justify-evenly bg-white">
```suggestion
    <div className="backdrop-blue-md fixed top-0 z-[100] mx-auto flex h-[77px] w-full items-center justify-evenly bg-white">
```

2024-08-06 18:09 UTC, k1nha commented on app/octopost/components/components/WaveAnimation.tsx
> +        zIndex: 1,
e o nosso tailwind?

2024-08-06 18:11 UTC, k1nha commented on app/octopost/layout.tsx
> +        <WhatIsOcto />
A mudança pro page não subiu, ainda ficou no layout

2024-08-06 18:47 UTC, merged