styles:footer
devhatt/devhatt-lp pull request #38
Opened 2024-08-28 19:48 UTC by Frompaje

Closes #2

![2024-08-28-16-44-26](https://github.com/user-attachments/assets/2b4b31e6-26b6-4032-a369-a0d200935a23)

2024-08-29 20:41 UTC, DominMFD requested changes

2024-08-30 11:53 UTC, k1nha commented on components/petdex/Footer/assets/Facebook.tsx
bom transformar todos os icones para receber props, como fazemos se quisermos mudar o tamanho do icone?

2024-08-30 11:57 UTC, k1nha commented on components/petdex/Footer/Footer.tsx
> +              <span className="border-[#E0E0E0] hover:border-b-[1px]">
os valores arbitrários não deveriam estar no tailwindconfig? `#E0E0E0` e `#1E2833`

2024-08-30 14:25 UTC, Luiginicoletti requested changes
Ficou top!!!

2024-08-30 14:25 UTC, Luiginicoletti commented on components/octopost/Datas/Datas.tsx
Por que foi feito alteração em componente do octopost?

2024-08-30 14:25 UTC, Luiginicoletti commented on components/petdex/Footer/Footer.tsx
> +            <a href="/">
Aqui como ta em next da pra usar a tag <Link>
```suggestion
            <Link href="/">
```

2024-08-30 14:25 UTC, Luiginicoletti commented on components/petdex/Footer/Footer.tsx
> +          </div>
da pra meter um .map() pra reaproveitar os <Link> e a estilizacao das div

2024-08-30 18:20 UTC, k1nha approved these changes

2024-09-03 17:40 UTC, DominMFD approved these changes

2024-09-06 03:21 UTC, aalmeida00 approved these changes

2024-09-06 03:21 UTC, merged

2024-09-07 00:56 UTC, RaulDelary commented
@PiluVitu, esse PR foi mergeado com erro no build. Talvez seja legal alterar o ruleset da branch para permitir o merge apenas com todos os cheks ok e instruir os codeowners a não bypassar o merge 😄 .

See [this](https://github.com/orgs/community/discussions/75568#discussioncomment-7570257). 

```
Failed to compile.

./components/petdex/Footer/Footer.tsx
14:24  Error: Replace `bg-petdex-darkBlueSecondary·flex·w-full·items-center·justify-center` with `flex·w-full·items-center·justify-center·bg-petdex-darkBlueSecondary`  prettier/prettier
15:23  Error: Replace `text-petdex-primayWhite·w-full` with `w-full·text-petdex-primayWhite`  prettier/prettier
40:25  Error: Replace `border-petdex-primayWhite·mx-auto·border-t-[1px]` with `mx-auto·border-t-[1px]·border-petdex-primayWhite`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

Em tempo, essas regras de lint fazem sentido? Se sim, acho interessante corrigir e tester novamente a demanda e fazer novo PR.

2024-09-07 01:01 UTC, PiluVitu commented
> @PiluVitu, esse PR foi mergeado com erro no build. Talvez seja legal alterar o ruleset da branch para permitir o merge apenas com todos os cheks ok e instruir os codeowners a não bypassar o merge 😄 .
> 
> See [this](https://github.com/orgs/community/discussions/75568#discussioncomment-7570257). 
> 
> ```
> Failed to compile.
> 
> ./components/petdex/Footer/Footer.tsx
> 14:24  Error: Replace `bg-petdex-darkBlueSecondary·flex·w-full·items-center·justify-center` with `flex·w-full·items-center·justify-center·bg-petdex-darkBlueSecondary`  prettier/prettier
> 15:23  Error: Replace `text-petdex-primayWhite·w-full` with `w-full·text-petdex-primayWhite`  prettier/prettier
> 40:25  Error: Replace `border-petdex-primayWhite·mx-auto·border-t-[1px]` with `mx-auto·border-t-[1px]·border-petdex-primayWhite`  prettier/prettier
> 
> info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
>  ELIFECYCLE  Command failed with exit code 1.
> Error: Process completed with exit code 1.
> ```
> 
> Em tempo, essas regras de lint fazem sentido? Se sim, acho interessante corrigir e tester novamente a demanda e fazer novo PR.

Pior que está essa configuração se não me engano, vou dar uma olhada e ver o porquê disso acontecer